### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/elinda#15]
* Change App name to Elinda
* Prefix: change : to dbr
* Title of diagram: X subclasses of ...
* Add PREFIX dbo: <http://dbpedia.org/ontology/> 
* Bug: when providing a first class, get title with owl:Thing
* Update tabs: "Subclasses", "Equivalent Classes"
* When presenting equivalent show title: X equivalent classes of ...
* Check logarithmic scale: https://www.amcharts.com/demos/logarithmic-scale/
* Update popup to table structure with the following info:
 * URI at the top (not in table)
 * rdfs:label | agent
 * #instances | xxx
 * #subclasses | xx
 * rdfs:comment | xyz

**Comment by Talyyy** [comment]
**update**
I finish working on list.
(need more work on the logarithmic scale )
