### ISSUE TITLE
Long class names are not presented correctly in the diagram

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/elinda#17]
For example, we loaded the endpoint https://linkeddata1.calcul.u-psud.fr/sparql with the graph http://www.yago-knowledge.org (YAGO) and since the URLs of the classes are quite long, the charts are not visible.

Possible correction: in case there is no rdfs:label to present, use the last string after the slash in the url.

**Comment by Talyyy** [comment]
I cut the uri -> show only last /
