### ISSUE TITLE
Add initial query: search for a subject based on textual keywords

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/elinda#2]
For example, the user enters "Netanyahu" and get subjects corresponding to that text. I suggest the following implementation that has reasonable performence:
SELECT * WHERE {
?s rdfs:label ?o. FILTER regex(?o, "netanyahu", "i"). 
} LIMIT 1
Note that we search based on rdfs:label.
The search is stopped when one instance is found. The user may be interested in adjusting the default limit (should it be 1?).

**Comment by Talyyy** [comment]
DONE

**Comment by omishali** [comment]
Well done Tal!
