### ISSUE TITLE
Number of instances should appear in all tabs after the class name

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/elinda#22]
For example, http://dbpedia.org/ontology/Philosopher (1,704)

**Comment by Talyyy** [comment]
done:)

**Comment by omishali** [comment]
Two comments:
* Add commas to the number (psikim)
* Add value also to owl:Thing (currently undefined)

2016-09-04 14:16 GMT+03:00 Talyyy <notifications@github.com>:
